# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_secondDialog(object):
    def setupUi(self, secondDialog):
        secondDialog.setObjectName("secondDialog")
        secondDialog.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(secondDialog.sizePolicy().hasHeightForWidth())
        secondDialog.setSizePolicy(sizePolicy)
        secondDialog.setStyleSheet("background-color: rgb(255, 255, 255);")

        # --- Main Layout for the entire dialog ---
        main_layout = QtWidgets.QVBoxLayout(secondDialog)
        main_layout.setContentsMargins(20, 20, 20, 20) # Add some margin around the edges

        # --- Image Label (Top Section) ---
        self.imageLable = QtWidgets.QLabel(secondDialog)
        # self.imageLable.setGeometry(QtCore.QRect(50, 10, 500, 200)) # REMOVE setGeometry when using layouts
        self.imageLable.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLable.setObjectName("imageLable")
        self.imageLable.setStyleSheet("border: 1px solid black; background-color: lightgray;")
        self.imageLable.setScaledContents(True) # Keep this for image scaling

        # Set a minimum size policy to ensure it has space even if nothing loads
        self.imageLable.setMinimumSize(300, 150)
        self.imageLable.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        main_layout.addWidget(self.imageLable, stretch=4) # Give it more vertical space

        # --- Horizontal Layout for Reset and Save Buttons ---
        button_layout = QtWidgets.QHBoxLayout()
        # self.resetButton.setGeometry(QtCore.QRect(200, 160, 75, 23)) # REMOVE setGeometry
        self.resetButton = QtWidgets.QPushButton(secondDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.resetButton.setObjectName("resetButton")

        # self.saveButton.setGeometry(QtCore.QRect(310, 160, 75, 23)) # REMOVE setGeometry
        self.saveButton = QtWidgets.QPushButton(secondDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.saveButton.setObjectName("saveButton")

        button_layout.addStretch(1) # Pushes buttons to center
        button_layout.addWidget(self.resetButton)
        button_layout.addWidget(self.saveButton)
        button_layout.addStretch(1) # Pushes buttons to center
        main_layout.addLayout(button_layout)


        # --- Controls Section using a Form Layout ---
        controls_layout = QtWidgets.QFormLayout()
        controls_layout.setContentsMargins(0, 20, 0, 0) # Add some top margin for separation

        # Transitions Combobox
        # self.transitionsLabel.setGeometry(QtCore.QRect(100, 240, 91, 21)) # REMOVE setGeometry
        self.transitionsLabel = QtWidgets.QLabel(secondDialog) # Re-create if you removed it for layout
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.transitionsLabel.setFont(font)
        self.transitionsLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.transitionsLabel.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter) # Align left in form layout
        self.transitionsLabel.setObjectName("transitionsLabel")

        # self.transitionCombobox.setGeometry(QtCore.QRect(260, 240, 201, 22)) # REMOVE setGeometry
        self.transitionCombobox = QtWidgets.QComboBox(secondDialog) # Re-create if you removed it for layout
        self.transitionCombobox.setObjectName("transitionCombobox")
        controls_layout.addRow(self.transitionsLabel, self.transitionCombobox)


        # Blur Slider
        # self.controlLabel.setGeometry(QtCore.QRect(90, 280, 91, 21)) # REMOVE setGeometry
        self.controlLabel = QtWidgets.QLabel(secondDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.controlLabel.setFont(font)
        self.controlLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.controlLabel.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.controlLabel.setObjectName("controlLabel")

        # self.blurSlider.setGeometry(QtCore.QRect(260, 280, 160, 16)) # REMOVE setGeometry
        self.blurSlider = QtWidgets.QSlider(secondDialog)
        self.blurSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blurSlider.setObjectName("blurSlider")
        controls_layout.addRow(self.controlLabel, self.blurSlider)


        # Brightness Slider
        # self.controlLabel_2.setGeometry(QtCore.QRect(90, 310, 91, 21)) # REMOVE setGeometry
        self.controlLabel_2 = QtWidgets.QLabel(secondDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.controlLabel_2.setFont(font)
        self.controlLabel_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.controlLabel_2.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.controlLabel_2.setObjectName("controlLabel_2")

        # self.brightnessSlider.setGeometry(QtCore.QRect(260, 310, 160, 16)) # REMOVE setGeometry
        self.brightnessSlider = QtWidgets.QSlider(secondDialog)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        controls_layout.addRow(self.controlLabel_2, self.brightnessSlider)


        # Rotation Angle Slider
        # self.controlLabel_3.setGeometry(QtCore.QRect(100, 340, 91, 21)) # REMOVE setGeometry
        self.controlLabel_3 = QtWidgets.QLabel(secondDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.controlLabel_3.setFont(font)
        self.controlLabel_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.controlLabel_3.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.controlLabel_3.setObjectName("controlLabel_3")

        # self.angleSlider.setGeometry(QtCore.QRect(260, 340, 160, 16)) # REMOVE setGeometry
        self.angleSlider = QtWidgets.QSlider(secondDialog)
        self.angleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.angleSlider.setObjectName("angleSlider")
        controls_layout.addRow(self.controlLabel_3, self.angleSlider)

        main_layout.addLayout(controls_layout, stretch=3) # Give controls some vertical space


        # self.horizontalLayoutWidget = QtWidgets.QWidget(secondDialog) # REMOVE
        # self.horizontalLayoutWidget.setGeometry(QtCore.QRect(189, 149, 211, 51))
        # self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        # self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        # self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        # self.horizontalLayout.setObjectName("horizontalLayout")

        # self.verticalLayoutWidget = QtWidgets.QWidget(secondDialog) # REMOVE
        # self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 220, 381, 171))
        # self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        # self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        # self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        # self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(secondDialog)
        QtCore.QMetaObject.connectSlotsByName(secondDialog)

    def retranslateUi(self, secondDialog):
        _translate = QtCore.QCoreApplication.translate
        secondDialog.setWindowTitle(_translate("secondDialog", "Dialog"))
        self.imageLable.setText(_translate("secondDialog", "Image will be displayed here"))
        self.transitionsLabel.setText(_translate("secondDialog", "TRANSITIONS"))
        self.controlLabel.setText(_translate("secondDialog", "Blur"))
        self.resetButton.setText(_translate("secondDialog", "RESET"))
        self.saveButton.setText(_translate("secondDialog", "SAVE"))
        self.controlLabel_2.setText(_translate("secondDialog", "Brightness"))
        self.controlLabel_3.setText(_translate("secondDialog", "Rotation Angle"))


