# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uploadDialog(object):
    def setupUi(self, uploadDialog):
        uploadDialog.setObjectName("uploadDialog")
        uploadDialog.resize(1111, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(uploadDialog.sizePolicy().hasHeightForWidth())
        uploadDialog.setSizePolicy(sizePolicy)
        uploadDialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.welcomeLabel = QtWidgets.QLabel(uploadDialog)
        self.welcomeLabel.setGeometry(QtCore.QRect(170, 30, 651, 131))
        font = QtGui.QFont()
        font.setFamily("Sitka Display Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("border-color: rgb(85, 0, 0);\n"
"background-color: rgb(170, 170, 127);")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.uploadButton = QtWidgets.QPushButton(uploadDialog)
        self.uploadButton.setGeometry(QtCore.QRect(370, 280, 281, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.uploadButton.setFont(font)
        self.uploadButton.setStyleSheet("border-color: rgb(85, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 85, 0);")
        self.uploadButton.setObjectName("uploadButton")

        self.retranslateUi(uploadDialog)
        QtCore.QMetaObject.connectSlotsByName(uploadDialog)

    def retranslateUi(self, uploadDialog):
        _translate = QtCore.QCoreApplication.translate
        uploadDialog.setWindowTitle(_translate("uploadDialog", "Dialog"))
        self.welcomeLabel.setText(_translate("uploadDialog", "WELCOME TO THE IMAGE TRANFORMER APP"))
        self.uploadButton.setText(_translate("uploadDialog", "UPLOAD IMAGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    uploadDialog = QtWidgets.QDialog()
    ui = Ui_uploadDialog()
    ui.setupUi(uploadDialog)
    uploadDialog.show()
    sys.exit(app.exec_())
